Bootstrap: docker
From: ubuntu:18.04

%labels
    Maintainer Belcour A.
    Version v1.1.6
    Description m2m Singularity recipe

%files
     pathway-tools-23.0-linux-64-tier1-install /tmp
     Oog.jar /tmp

%environment
     export PATH="$PATH:/programs/pathway-tools:"
     export PATH="$PATH:/programs/Oog.jar:"
     export PYTHONIOENCODING=utf8

%post
     apt-get -y update && \
     DEBIAN_FRONTEND=noninteractive apt-get install -y \
     curl \
     csh \
     git \
     ncbi-blast+ \
     libxm4 \
     python3.6-dev \
     python3.6-distutils \
     default-jre \
     iputils-ping \
     gnome-terminal;\
     apt-get clean; \
     apt-get purge; \
     mkdir /programs;\
     mv /tmp/Oog.jar /programs;\
     mkdir -p /external/folder;\
     chmod u+x /tmp/pathway-tools-23.0-linux-64-tier1-install;\
     ./tmp/pathway-tools-23.0-linux-64-tier1-install --InstallDir /programs/pathway-tools --PTOOLS_LOCAL_PATH /external/folder --InstallDesktopShortcuts 0 --mode unattended;\
     mkdir -p /opt;\
     cp -r /external/folder/ptools-local /opt;\
     rm /tmp/pathway-tools-23.0-linux-64-tier1-install;\
     curl https://bootstrap.pypa.io/get-pip.py | python3;\
     pip install graphviz ete3 networkx;\
     pip install powergrasp;\
     pip install Metage2Metabo