Bootstrap: docker
From: ubuntu:18.04

%files
     pathway-tools-23.0-linux-64-tier1-install /tmp

%environment
     export PATH="$PATH:/programs/pathway-tools:"

%post
     apt-get -y update && \
     DEBIAN_FRONTEND=noninteractive apt-get install -y \
     curl \
     csh \
     git \
     ncbi-blast+ \
     libxm4 \
     python3.6-dev \
     python3.6-distutils \
     iputils-ping \
     gnome-terminal;\
     apt-get clean; \
     apt-get purge; \
     mkdir programs;\
     mkdir -p /external/folder/ptools;\
     chmod u+x /tmp/pathway-tools-23.0-linux-64-tier1-install;\
     ./tmp/pathway-tools-23.0-linux-64-tier1-install --InstallDir /programs/pathway-tools --PTOOLS_LOCAL_PATH /external/folder/ptools --InstallDesktopShortcuts 0 --mode unattended;\
     mkdir -p /opt/ptools;\
     cp -r /external/folder/ptools  /opt/ptools;\
     rm /tmp/pathway-tools-23.0-linux-64-tier1-install;\
     curl https://bootstrap.pypa.io/get-pip.py | python3;\
     pip install Metage2Metabo