dist: trusty
sudo: required
language: python
python:
  - "3.6"

# Install packages
before_script:
- python setup.py develop
- cd test

script:
- pytest test_m2m_addedvalue.py --disable-pytest-warnings
- pytest test_m2m_mincom.py --disable-pytest-warnings
