dist: trusty
sudo: required
language: python
python:
  - "3.6"

# Install packages
install:
  - pip install Metage2Metabo

script:
- pytest test/test_m2m_addedvalue.py --disable-pytest-warnings
- pytest test/test_m2m_mincom.py --disable-pytest-warnings
